export const MAIN_NAMESPACE_EVENTS = {
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
  START_GAME: "start::game",
  RESTART_GAME: "restart::game",
  END_GAME: "end::game",
  JOIN_ROOM: "join::room",
  LEAVE_ROOM: "leave::room",
  NEW_PLAYER_JOINED: "player::joined",
  PLAYER_DISCONNECTED: "player::disconnected",
  SEND_MESSAGE: "send::message",
  NEW_MESSAGE: "new::message",
  ROOM_FULL: "room::full",
  CARDS_GENERATED: "cards::generated",
  BID_POINT: "bid::point",
  NEW_BID: "new::bid",
};
